"""irando a columa on_menu para teste

Revision ID: c113e22d5dbf
Revises: 
Create Date: 2021-10-11 18:52:10.626830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c113e22d5dbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'on_menu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('on_menu', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
