# This workflow will install Python dependencies and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
defaults:
  run:
    shell: powershell
    working-directory: ./delivery

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r "../requirements.txt"
        pip install pytest
        pip install pytest-flask
        pip install flask-debugtoolbar
        pip install ..
    - name: Test with pytest
      working-directory: ../.
      run: |
        pytest 
